### ISSUE TITLE
classloader object release problem

### ISSUE THREAD

**Issue by HaoWangDL** [pefoo/CPP-Dynamic-ClassLoader#1]
Thank you very much for providing the classloader dynamic library package.

Step1: Loading two different dynamic libraries in the main function, for example，auto cl = new ClassLoader(GetLib()) and auto cl2 = new ClassLoader(GetLib()); 
Step2: Using delete cl1; delete cl2 at the end of main() function;

Then will result in segment error，and cannot destruct class in library at the same time, What's the reason?

thanks!

**Comment by HaoWangDL** [comment]
@pefoo

**Comment by pefoo** [comment]
@HaoWangDL Good point. The old version of the sample should have thrown the exception too. 

The reason for the segmentation fault is destruction order. If you close the shared library before actually deleting the loaded classes, a segmentation fault occurs as soon as the smart pointer (which holds the loaded class) tries to delete said class. This is because the loaded destructor is no longer available (since the library is closed already)

To fix this, you have to take care for destruction order. 

1. Destroy all loaded classes 
2. Destroy the class loader

**Comment by HaoWangDL** [comment]
It's too deep into the underlying mechanism, I see. Thank you.
@pefoo
